name: AFKOps
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

# Application versioning
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.6.1

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI and State Management
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Storage & Utilities
  uuid: ^4.5.1
  intl: ^0.19.0

  # Device and Network
  local_auth: ^2.3.0
  connectivity_plus: ^6.1.2
  wifi_iot: ^0.3.19+1
  permission_handler: ^11.3.1

  # SSH and API Communication
  dartssh2: ^2.11.0
  http: ^1.3.0
  web_socket_channel: ^2.4.5

  # App Icons
  flutter_launcher_icons: ^0.14.3

  # Splash Screen
  flutter_native_splash: ^2.4.0
  encrypt: ^5.0.3
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^8.1.0
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

# App Icons Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Ensure this file exists
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"

# Splash Screen Configuration
flutter_native_splash:
  color: "#B0C0C2"
  image: "assets/splash.png"  # Ensure this file exists
  android_12:
    image: "assets/splash.png"
    icon_background_color: "#B0C0C2"
  fullscreen: true

# Flutter Settings
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/icon.png
    - assets/splash.png

  # Fonts (Add if needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
